matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang

language: c

branches:
  only:
    - release

cache:
  directories:
    - "$HOME/.electron"
    - "./node_modules"

addons:
  apt:
    packages:
      - bsdtar
      - g++-multilib
      - gcc-multilib
      - graphicsmagick
      - icnsutils
      - libicns-dev
      - libpng-dev
      - libpng12-0
      - rpm
      - xz-utils

before_install:
  - echo "ðŸ”§ Installing tools"
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | NVM_DIR=$HOME/.nvm sh
  - source $HOME/.nvm/nvm.sh
  - nvm install 7.7.2
  - nvm use 7.7.2

install:
  - echo "ðŸ“¥ Installing dependencies"
  - npm install

script:
  - echo "ðŸ“¦ Building artifacts"
  - npm run-script build

after_success:
  - echo "ðŸ“® Deploying artifacts"
  - npm run-script deploy:github

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/24d905038aa07dda37df
    on_success: change
    on_failure: always
    on_start: never

