matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      group: edge
      compiler: clang

language: c

branches:
  only:
    - master

cache:
  directories:
    - "./node_modules"
    - "${HOME}/.yarn-cache"

addons:
  apt:
    packages:
      - bsdtar
      - g++-multilib
      - gcc-multilib
      - graphicsmagick
      - icnsutils
      - rpm
      - xz-utils

before_install:
  - echo "ðŸš¦ Authorizing Build"
  - echo "ðŸ”§ Setting up Node"
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | NVM_DIR="${HOME}"/.nvm sh
  - source "${HOME}"/.nvm/nvm.sh && nvm install 9.3.0 && nvm use 9.3.0
  - npm --global update npm
  - npm --global install yarn

install:
  - echo "ðŸ“¥ Installing Dependencies"
  - yarn install

script:
  - echo "ðŸ“¦ Building"
  - npm run build --metadata

after_success:
  - echo "ðŸ“® Deploying to Github"
  - npm run deploy

notifications:
  webhooks:
    on_failure: always
    on_start: never
    on_success: change
    urls:
      - https://webhooks.gitter.im/e/24d905038aa07dda37df
