matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      sudo: required
    - os: linux
      sudo: required
      dist: trusty
      group: edge
      compiler: clang

language: c

branches:
  only:
    - master

cache:
  directories:
    - "./node_modules"
    - "${HOME}/.yarn-cache"

addons:
  apt:
    packages:
      - bsdtar
      - g++-multilib
      - gcc-multilib
      - graphicsmagick
      - icnsutils
      - rpm
      - xz-utils

before_install:
  - echo "ðŸš¦ Authorizing Build"
  - if [[ "${OSTYPE}" == "darwin"* ]] && [[ "${DEPLOY_MACOS}" == 0 ]]; then travis_terminate 0; fi
  - if [[ "${OSTYPE}" == "linux"* ]] && [[ "${DEPLOY_LINUX}" == 0 ]]; then travis_terminate 0; fi
  - echo "ðŸ”§ Setting up Environment"
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | NVM_DIR="${HOME}"/.nvm sh
  - source "${HOME}"/.nvm/nvm.sh && nvm install 8.5.0 && nvm use 8.5.0
  - npm --global update npm
  - npm --global install yarn

install:
  - echo "ðŸ“¥ Installing Dependencies"
  - npm install
  - yarn install

script:
  - echo "ðŸ“¦ Building"
  - npm run build --metadata

after_success:
  - echo "ðŸ“® Deploying"
  - npm run deploy

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/24d905038aa07dda37df
    on_success: change
    on_failure: always
    on_start: never

