matrix:
  include:
    - os: linux
      dist: bionic
      group: edge
      compiler: clang

language: c

branches:
  only:
    - master

env:
  global:
    - LC_ALL: "C.UTF-8"
    - LANG: "C.UTF-8"
    - PATH: "/snap/bin:${PATH}"

cache:
  directories:
    - "./node_modules"
    - "${HOME}/.yarn-cache"
    - ${TRAVIS_BUILD_DIR}/snaps-cache

addons:
  apt:
    packages:
      - bsdtar
      - g++-multilib
      - gcc-multilib
      - graphicsmagick
      - icnsutils
      - libopenjp2-tools
      - libxss-dev:i386
      - rpm
      - snapd
      - xz-utils
  snaps:
    - name: multipass
      confinement: classic
      channel: edge
    - name: snapcraft
      confinement: classic
      channel: edge

before_install:
  - echo "ðŸ”§ Preparing Build Environment (Node.js)"
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | NVM_DIR="${HOME}"/.nvm sh
  - source "${HOME}"/.nvm/nvm.sh && nvm install 13.1.0 && nvm use 13.1.0
  - npm --global update npm
  - npm --global install yarn

install:
  - echo "ðŸ“¥ Installing Dependencies"
  - yarn install

script:
  - echo "ðŸ“¦ Building Project"
  - npm run build

after_success:
  - echo "ðŸ“® Deploying Project"
  - npm run deploy

notifications:
  webhooks:
    on_failure: always
    on_start: never
    on_success: change
    urls:
      - https://webhooks.gitter.im/e/24d905038aa07dda37df
